### ISSUE TITLE
Step 2 sometimes doesn't have syntax highlighting

### ISSUE THREAD

**Issue by valentingoebel** [aturley/pony-workshop#8]
The first example in the [readme](https://github.com/aturley/pony-workshop/blob/master/steps/02/README.md) for the second step doesn't have syntax highlighting. 
I assume the problem is that `ponyc` isn't a valid keyword for syntax highlighting but `pony` is.

```
```ponyc
```

**Comment by aturley** [comment]
Ah, thanks, good catch!
