### ISSUE TITLE
01 - Q3 suggests that local variables could start with a `_` (but they can't?)

### ISSUE THREAD

**Issue by wryun** [aturley/pony-workshop#9]
```
; ponyc --pic
Building builtin -> /usr/lib/pony/0.24.3-1/packages/builtin
Building . -> /home/jamesh/a/learn/pony-workshop/steps/01
Error:
/home/jamesh/a/learn/pony-workshop/steps/01/main.pony:3:9: local variable name "_msg" cannot start with underscores
    let _msg = "hello world"
        ^
```

**Comment by aturley** [comment]
Ah, that's a good point. The underscore is used to make a field private, but I don't really make that clear. I think when I wrote it I thought that being vague might stimulate an investigation, but I realize that I don't give any information that one could use to look into what's going on. I should probably have a link to the section of the tutorial that covers variables and naming (https://tutorial.ponylang.org/expressions/variables.html).

**Comment by aturley** [comment]
@wryun what do you think of the change in this PR #10?

**Comment by wryun** [comment]
Looks good to me, but I know nothing about Pony, just started running through your workshop (excellent introduction - thanks!).
